import type { Metadata } from "next";
import { volkhov, poppins } from "./fonts/fonts";
import "./globals.css";
import PaddingContainer from "@/components/Common/PaddingContainer/PaddingContainer";

export const metadata: Metadata = {
  title: "Jadoo-Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ volkhov.className } ${ poppins.className }antialiased`}>
        <PaddingContainer>{children}</PaddingContainer>
      </body>
    </html>
  );
}
